apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds.yaml
- deployment.yaml
- flux-account.yaml
- flux-deployment.yaml
- flux-namespace.yaml
- flux-secret.yaml
- memcache-dep.yaml
- memcache-svc.yaml
- rbac.yaml
